# Generated by Django 4.1 on 2022-09-02 21:43

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('food_image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='food/%Y/%m/')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
            ],
            options={
                'verbose_name': 'food',
                'verbose_name_plural': 'food',
                'db_table': 'food',
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_of_store', models.PositiveSmallIntegerField(default=10, verbose_name='storage')),
                ('day', models.CharField(choices=[('0', 'everyday'), ('1', 'saturday'), ('2', 'sunday'), ('3', 'monday'), ('4', 'tuesday'), ('5', 'wednesday')], max_length=1, verbose_name='day')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('price', models.PositiveIntegerField(default=1000, verbose_name='price')),
                ('food_type', models.CharField(choices=[('1', 'subsidy'), ('2', 'non-subsidy')], default=1, max_length=10)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='core.food')),
            ],
            options={
                'verbose_name': 'food item',
                'verbose_name_plural': 'food items',
                'db_table': 'food_item',
                'unique_together': {('food', 'day')},
            },
        ),
    ]
